In [1]:
pip install numpy

  Using cached numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl (5.3 MB)

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# create arrays using numpy
# create 1 d array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
# 2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Array:\n{arr}")
print(f"Shape of array: {arr.shape}")
print(f"Number of dimensions: {arr.ndim}")
print(f"Data type of array: {arr.dtype}")
print(f"Size of array: {arr.size}")
print(f"Item size of array: {arr.itemsize} bytes")


Array:
[[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)
Number of dimensions: 2
Data type of array: int64
Size of array: 6
Item size of array: 8 bytes


In [18]:
# Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print(f"Addition::::{arr1 + arr2}")

# Elemt wise substraction
print(f"Substraction::::{arr1 - arr2}")
# element wise multiplication
print(f"Multiplication::::{arr1 * arr2}")
# element wise division
print(f"Division::::{arr1 / arr2}")


Addition::::[11 22 33 44 55]
Substraction::::[ -9 -18 -27 -36 -45]
Multiplication::::[ 10  40  90 160 250]
Division::::[0.1 0.1 0.1 0.1 0.1]


In [19]:
# Universal functions in numpy
arr = np.array([1,2,3,4,5])
print(f"Square root::::{np.sqrt(arr)}")
print(f"Exponential::::{np.exp(arr)}")
print(f"Logarithm::::{np.log(arr)}")
print(f"Sine::::{np.sin(arr)}")
print(f"Cosine::::{np.cos(arr)}")
print(f"Tangent::::{np.tan(arr)}")






Square root::::[1.         1.41421356 1.73205081 2.         2.23606798]
Exponential::::[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm::::[0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine::::[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine::::[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangent::::[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [20]:
# array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Original array:\n{arr}")

# Accessing elements
print(f"Element at (0,0): {arr[0,0]}")
print(f"Element at (1,2): {arr[1,2]}")

# Slicing
print(f"First row: {arr[0,:]}")
print(f"First column: {arr[:,0]}")
print(f"Subarray (1:3, 1:3):\n{arr[1:3, 1:3]}")





Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0,0): 1
Element at (1,2): 6
First row: [1 2 3]
First column: [1 4 7]
Subarray (1:3, 1:3):
[[5 6]
 [8 9]]


In [3]:
#  Normalisation

# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calc mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean)/std_dev
print(f"Normalized data::::{normalized_data}")

Normalized data::::[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [8]:
# Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])